### ISSUE TITLE
better integration with AIRR standards doc website

### ISSUE THREAD

**Issue by schristley** [airr-community/ogrdb#51]
While OGRE provides documentation within its website, which is great, we should also give OGRE a prominent spot at the AIRR standards [docs](https://docs.airr-community.org/) with information about how it integrates with the rest of the AIRR stuff.

**Comment by williamdlees** [comment]
Scott, what should I do about this? Should I write a section in the standards doc? On OGRDB generally, or specifically on data structure and potential standards?

**Comment by schristley** [comment]
With the doc restructure, I added a [section](http://docs.airr-community.org/en/latest/standards/data_submission.html) about data submission. That might be sufficient but maybe give it a read to see if anything is missing. While there is information/workflow on submission, I don't have anything for query and download.
