### ISSUE TITLE
Publish schema in more accessible format

### ISSUE THREAD

**Issue by williamdlees** [airr-community/ogrdb#66]
From Erick Matsen - I also suggest making the schema a little more prominent. It looks like it's in YAML-- is it a JSONschema? Can it be digested to an HTML file or some sort of diagram? 

Important particularly to promote the aspects that we would like to promote more widely, such as the germline reference set.

**Comment by schristley** [comment]
I had meant to help you do this but unfortunately never got around to it. The schema is close to being compliant with the OpenAPI V2 spec (as like the rest of the AIRR Standards) but needs some cleanup. Once it is compliant, then I imagine there are any number of tools that can parse/visualize/analyze/etc the schema.

**Comment by schristley** [comment]
I was also hesitant because I think you use the schema to drive functionality for the web site, so updating the schema will likely required code changes.

**Comment by williamdlees** [comment]
I had a look at this today and decided, for the time being at least, to leave the schema definition as it is. A couple of reasons for this:
- Only about half the tables in the schema are useful from the point of view of understanding the 'business' data structure. The others are related to user management, cacheing, or are link tables of one sort or another. As I can produce reasonably nice diagrams from MySQL Workbench, albeit with some manual intervention, I've put together a relationship diagram for the key objects which can be found here: https://github.com/airr-community/ogrdb/blob/master/schema/OGRDB_simplified_database_model.pdf . There's a link in the introduction on the home page.
- I think it's best if the formal definition of any AIRR Standard objects is done outside the OGRDB code base. I'm certainly happy to contribute, and may well ingest it in OGRDB when it's complete. That feels like the best way round to me: the standard should drive OGRDB rather than the other way around.

Will leave this thread open for a while in case there are comments.
